// app/layout.tsx
import "../styles/globals.css";
import Header from "../components/layout/Header";
import Footer from "../components/layout/Footer";
import Contato from "../components/layout/Contato";

export const metadata = {
  title: "GritoWeb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body>
        <div className="px-8 py-6 bg-background lg:px-32">
          <Header />
        </div>
        <div>{children}</div>
        <div className="px-8 pt-6 bg-background lg:px-32">
          <Contato />
        </div>
        <div className="px-8 py-6 bg-primary lg:px-32">
          <Footer />
        </div>
      </body>
    </html>
  );
}
