// app/layout.tsx
import "../styles/globals.css";
import Header from "../components/layout/Header";
import Footer from "../components/layout/Footer";
import Contato from "../components/layout/Contato";

export const metadata = {
  title: "GritoWeb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body>
        <div className="pt-8 px-8 lg:px-0">
          <Header />
        </div>
        <div>{children}</div>
        <div className="px-8 lg:px-0">
          <Contato />
        </div>
        <div className="bg-primary absolute w-[100vw] left-0 bottom -0">
          <Footer />
        </div>
      </body>
    </html>
  );
}
