import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import Contato from "./components/Contato";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <div className="px-8 py-6 bg-background lg:px-32">
          <Header/>
        </div>
        <div>
          {children}
        </div>
        <div>
          <Contato />
        </div>
        <div className="px-8 py-6 bg-primary lg:px-32">
          <Footer />
        </div>
      </body>
    </html>
  );
}
